development:
  adapter: postgresql
  encoding: unicode
  database: journal_development
  pool: 5
  username: belkiii
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: journal_test
  pool: 5
  username: belkiii
  password:
